name = "releaseparty"
compatibility_date = "2026-01-02"
compatibility_flags = ["nodejs_compat"]
main = ".svelte-kit/cloudflare/_worker.js"

[assets]
directory = ".svelte-kit/cloudflare/_app"
binding = "__STATIC_CONTENT"
